apiVersion: v1
kind: Service
metadata:
  name: kubeglance-backend
  namespace: kubeglance
  labels:
    {{- include "kubeglance.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "kubeglance.backend.selectorLabels" . | nindent 6 }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: 3000
  type: {{ .Values.frontend.service.type }}
