apiVersion: v1
kind: Service
metadata:
  name: kubeglance-frontend
  namespace: kubeglance
  labels:
    {{- include "kubeglance.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "kubeglance.frontend.selectorLabels" . | nindent 6 }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: 80
  type: {{ .Values.frontend.service.type }}
